# Copyright 2011 Securepoint GmbH


MAJOR_VERSION=0
MINOR_VERSION=9
PATCH_VERSION=0
BUILD="rc1"

DEFINES += MAJOR_VERSION=$$MAJOR_VERSION MINOR_VERSION=$$MINOR_VERSION PATCH_VERSION=$$PATCH_VERSION BUILD=$$BUILD
